require 'spec_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to specify the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator.  If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails.  There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.
#
# Compared to earlier versions of this generator, there is very limited use of
# stubs and message expectations in this spec.  Stubs are only used when there
# is no simpler way to get a handle on the object needed for the example.
# Message expectations are only used when there is no simpler way to specify
# that an instance is receiving a specific message.

describe CrimeTypeDescriptionsController do

  # This should return the minimal set of attributes required to create a valid
  # CrimeTypeDescription. As you add validations to CrimeTypeDescription, be sure to
  # adjust the attributes here as well.
  let(:valid_attributes) { {  } }

  # This should return the minimal set of values that should be in the session
  # in order to pass any filters (e.g. authentication) defined in
  # CrimeTypeDescriptionsController. Be sure to keep this updated too.
  let(:valid_session) { {} }

  describe "GET index" do
    it "assigns all crime_type_descriptions as @crime_type_descriptions" do
      crime_type_description = CrimeTypeDescription.create! valid_attributes
      get :index, {}, valid_session
      assigns(:crime_type_descriptions).should eq([crime_type_description])
    end
  end

  describe "GET show" do
    it "assigns the requested crime_type_description as @crime_type_description" do
      crime_type_description = CrimeTypeDescription.create! valid_attributes
      get :show, {:id => crime_type_description.to_param}, valid_session
      assigns(:crime_type_description).should eq(crime_type_description)
    end
  end

  describe "GET new" do
    it "assigns a new crime_type_description as @crime_type_description" do
      get :new, {}, valid_session
      assigns(:crime_type_description).should be_a_new(CrimeTypeDescription)
    end
  end

  describe "GET edit" do
    it "assigns the requested crime_type_description as @crime_type_description" do
      crime_type_description = CrimeTypeDescription.create! valid_attributes
      get :edit, {:id => crime_type_description.to_param}, valid_session
      assigns(:crime_type_description).should eq(crime_type_description)
    end
  end

  describe "POST create" do
    describe "with valid params" do
      it "creates a new CrimeTypeDescription" do
        expect {
          post :create, {:crime_type_description => valid_attributes}, valid_session
        }.to change(CrimeTypeDescription, :count).by(1)
      end

      it "assigns a newly created crime_type_description as @crime_type_description" do
        post :create, {:crime_type_description => valid_attributes}, valid_session
        assigns(:crime_type_description).should be_a(CrimeTypeDescription)
        assigns(:crime_type_description).should be_persisted
      end

      it "redirects to the created crime_type_description" do
        post :create, {:crime_type_description => valid_attributes}, valid_session
        response.should redirect_to(CrimeTypeDescription.last)
      end
    end

    describe "with invalid params" do
      it "assigns a newly created but unsaved crime_type_description as @crime_type_description" do
        # Trigger the behavior that occurs when invalid params are submitted
        CrimeTypeDescription.any_instance.stub(:save).and_return(false)
        post :create, {:crime_type_description => {  }}, valid_session
        assigns(:crime_type_description).should be_a_new(CrimeTypeDescription)
      end

      it "re-renders the 'new' template" do
        # Trigger the behavior that occurs when invalid params are submitted
        CrimeTypeDescription.any_instance.stub(:save).and_return(false)
        post :create, {:crime_type_description => {  }}, valid_session
        response.should render_template("new")
      end
    end
  end

  describe "PUT update" do
    describe "with valid params" do
      it "updates the requested crime_type_description" do
        crime_type_description = CrimeTypeDescription.create! valid_attributes
        # Assuming there are no other crime_type_descriptions in the database, this
        # specifies that the CrimeTypeDescription created on the previous line
        # receives the :update_attributes message with whatever params are
        # submitted in the request.
        CrimeTypeDescription.any_instance.should_receive(:update).with({ "these" => "params" })
        put :update, {:id => crime_type_description.to_param, :crime_type_description => { "these" => "params" }}, valid_session
      end

      it "assigns the requested crime_type_description as @crime_type_description" do
        crime_type_description = CrimeTypeDescription.create! valid_attributes
        put :update, {:id => crime_type_description.to_param, :crime_type_description => valid_attributes}, valid_session
        assigns(:crime_type_description).should eq(crime_type_description)
      end

      it "redirects to the crime_type_description" do
        crime_type_description = CrimeTypeDescription.create! valid_attributes
        put :update, {:id => crime_type_description.to_param, :crime_type_description => valid_attributes}, valid_session
        response.should redirect_to(crime_type_description)
      end
    end

    describe "with invalid params" do
      it "assigns the crime_type_description as @crime_type_description" do
        crime_type_description = CrimeTypeDescription.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        CrimeTypeDescription.any_instance.stub(:save).and_return(false)
        put :update, {:id => crime_type_description.to_param, :crime_type_description => {  }}, valid_session
        assigns(:crime_type_description).should eq(crime_type_description)
      end

      it "re-renders the 'edit' template" do
        crime_type_description = CrimeTypeDescription.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        CrimeTypeDescription.any_instance.stub(:save).and_return(false)
        put :update, {:id => crime_type_description.to_param, :crime_type_description => {  }}, valid_session
        response.should render_template("edit")
      end
    end
  end

  describe "DELETE destroy" do
    it "destroys the requested crime_type_description" do
      crime_type_description = CrimeTypeDescription.create! valid_attributes
      expect {
        delete :destroy, {:id => crime_type_description.to_param}, valid_session
      }.to change(CrimeTypeDescription, :count).by(-1)
    end

    it "redirects to the crime_type_descriptions list" do
      crime_type_description = CrimeTypeDescription.create! valid_attributes
      delete :destroy, {:id => crime_type_description.to_param}, valid_session
      response.should redirect_to(crime_type_descriptions_url)
    end
  end

end
